<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BytemountsAiStudio.Workflow\BytemountsAiStudio.Workflow.csproj" />
    <ProjectReference Include="..\BytemountsAiStudio.Queue\BytemountsAiStudio.Queue.csproj" />
    <ProjectReference Include="..\BytemountsAiStudio.Persistence\BytemountsAiStudio.Persistence.csproj" />
    <ProjectReference Include="..\BytemountsAiStudio.Providers.Fake\BytemountsAiStudio.Providers.Fake.csproj" />
    <ProjectReference Include="..\BytemountsAiStudio.Media.Rendering\BytemountsAiStudio.Media.Rendering.csproj" />
    <ProjectReference Include="..\BytemountsAiStudio.Media\BytemountsAiStudio.Media.csproj" />
    <ProjectReference Include="..\BytemountsAiStudio.Nodes\BytemountsAiStudio.Nodes.csproj" />
    <ProjectReference Include="..\BytemountsAiStudio.Providers.Open\BytemountsAiStudio.Providers.Open.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
