<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\BytemountsAiStudio.Quality\BytemountsAiStudio.Quality.csproj" />
    <ProjectReference Include="..\BytemountsAiStudio.Workflow\BytemountsAiStudio.Workflow.csproj" />
    <ProjectReference Include="..\BytemountsAiStudio.Media.Rendering\BytemountsAiStudio.Media.Rendering.csproj" />
    <ProjectReference Include="..\BytemountsAiStudio.Providers.Fake\BytemountsAiStudio.Providers.Fake.csproj" />
    <ProjectReference Include="..\BytemountsAiStudio.Persistence\BytemountsAiStudio.Persistence.csproj" />
    <ProjectReference Include="..\BytemountsAiStudio.Providers.Open\BytemountsAiStudio.Providers.Open.csproj" />
    <ProjectReference Include="..\BytemountsAiStudio.Providers.Llm\BytemountsAiStudio.Providers.Llm.csproj" />
  </ItemGroup>
</Project>
