// <auto-generated />
using System;
using BytemountsAiStudio.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace BytemountsAiStudio.Persistence.Migrations
{
    [DbContext(typeof(StudioDbContext))]
    [Migration("20260828001603_RetryLoops")]
    partial class RetryLoops
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("decided_by");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("node_id");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_approvals");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_approvals_pending")
                        .HasFilter("state = 0");

                    b.HasIndex("RunId", "NodeId")
                        .IsUnique()
                        .HasDatabaseName("ux_approvals_pending_node")
                        .HasFilter("state = 0");

                    b.ToTable("approvals", (string)null);
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.Asset", b =>
                {
                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("sha256")
                        .IsFixedLength();

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("LicenseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("license_json");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mime_type");

                    b.Property<string>("SourceProvider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_provider");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_url");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Sha256")
                        .HasName("pk_assets");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_assets_kind");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DailyBudget")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("daily_budget");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paused");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language");

                    b.Property<decimal?>("MaxCostPerVideo")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("max_cost_per_video");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_json");

                    b.HasKey("Id")
                        .HasName("pk_channels");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_channels_name");

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.ClaimRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<bool>("SameModel")
                        .HasColumnType("boolean")
                        .HasColumnName("same_model");

                    b.Property<int>("SentenceIndex")
                        .HasColumnType("integer")
                        .HasColumnName("sentence_index");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("verdict");

                    b.HasKey("Id")
                        .HasName("pk_claims");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_claims_source_id");

                    b.HasIndex("RunId", "Verdict")
                        .HasDatabaseName("ix_claims_run_id_verdict");

                    b.ToTable("claims", (string)null);
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<string>("CipherText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cipher_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Masked")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("masked");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_credentials");

                    b.HasIndex("ProviderKey")
                        .IsUnique()
                        .HasDatabaseName("ix_credentials_provider_key")
                        .HasFilter("channel_id IS NULL");

                    b.HasIndex("ChannelId", "ProviderKey")
                        .IsUnique()
                        .HasDatabaseName("ix_credentials_channel_id_provider_key")
                        .HasFilter("channel_id IS NOT NULL");

                    b.ToTable("credentials", (string)null);
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FairKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fair_key");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeasedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("leased_by");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("NodeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("node_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("queue");

                    b.Property<DateTimeOffset>("RunAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_after");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("LeaseExpiresAt")
                        .HasDatabaseName("ix_jobs_lease_expires_at")
                        .HasFilter("state = 'Leased'");

                    b.HasIndex("Queue", "RunAfter", "Priority")
                        .HasDatabaseName("ix_jobs_queue_run_after_priority")
                        .HasFilter("state = 'Pending'");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.NodeExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("error_json");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("Loop")
                        .HasColumnType("integer")
                        .HasColumnName("loop");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("node_id");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("node_type");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_json");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_node_executions");

                    b.HasIndex("IdempotencyKey")
                        .HasDatabaseName("ix_node_executions_idempotency_key");

                    b.HasIndex("RunId", "NodeId", "Loop", "Attempt")
                        .IsUnique()
                        .HasDatabaseName("ix_node_executions_run_id_node_id_loop_attempt");

                    b.ToTable("node_executions", (string)null);
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.ProviderCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("NodeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("node_id");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operation");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_key");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.Property<string>("UnitsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("units_json");

                    b.HasKey("Id")
                        .HasName("pk_provider_calls");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_provider_calls_created_at");

                    b.HasIndex("RunId", "CreatedAt")
                        .HasDatabaseName("ix_provider_calls_run_id_created_at");

                    b.ToTable("provider_calls", (string)null);
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ActualCost")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("actual_cost");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("context_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("error_json");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("estimated_cost");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("RetryLoop")
                        .HasColumnType("integer")
                        .HasColumnName("retry_loop");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<Guid>("WorkflowVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_version_id");

                    b.HasKey("Id")
                        .HasName("pk_runs");

                    b.HasIndex("WorkflowVersionId")
                        .HasDatabaseName("ix_runs_workflow_version_id");

                    b.HasIndex("State", "CreatedAt")
                        .HasDatabaseName("ix_runs_state_created_at")
                        .HasFilter("state IN ('Pending', 'Running', 'WaitingApproval', 'WaitingResource')");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.RunEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("data_json");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<string>("NodeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("node_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.HasKey("Id")
                        .HasName("pk_run_events");

                    b.HasIndex("RunId", "CreatedAt")
                        .HasDatabaseName("ix_run_events_run_id_created_at");

                    b.ToTable("run_events", (string)null);
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_settings");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("content_hash")
                        .IsFixedLength();

                    b.Property<int>("ContentLength")
                        .HasColumnType("integer")
                        .HasColumnName("content_length");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("excerpt");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<double>("TrustScore")
                        .HasColumnType("double precision")
                        .HasColumnName("trust_score");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_sources");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_sources_content_hash");

                    b.HasIndex("Url")
                        .HasDatabaseName("ix_sources_url");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Angle")
                        .HasColumnType("text")
                        .HasColumnName("angle");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language");

                    b.Property<double>("OverallScore")
                        .HasColumnType("double precision")
                        .HasColumnName("overall_score");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text")
                        .HasColumnName("rejected_reason");

                    b.Property<string>("ScoresJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scores_json");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_topics");

                    b.HasIndex("ChannelId", "Language")
                        .HasDatabaseName("ix_topics_channel_id_language");

                    b.HasIndex("State", "OverallScore")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_topics_state_overall_score")
                        .HasFilter("state IN ('New', 'Queued')");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<string>("ContentKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("content_kind");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("current_version");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_workflows_key");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.WorkflowVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GraphJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("graph_json");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_versions");

                    b.HasIndex("WorkflowId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_versions_workflow_id_version");

                    b.ToTable("workflow_versions", (string)null);
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.Approval", b =>
                {
                    b.HasOne("BytemountsAiStudio.Persistence.Entities.Run", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approvals_runs_run_id");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.ClaimRecord", b =>
                {
                    b.HasOne("BytemountsAiStudio.Persistence.Entities.Run", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_claims_runs_run_id");

                    b.HasOne("BytemountsAiStudio.Persistence.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_claims_sources_source_id");

                    b.Navigation("Run");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.Credential", b =>
                {
                    b.HasOne("BytemountsAiStudio.Persistence.Entities.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_credentials_channels_channel_id");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.NodeExecution", b =>
                {
                    b.HasOne("BytemountsAiStudio.Persistence.Entities.Run", "Run")
                        .WithMany("NodeExecutions")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_executions_runs_run_id");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.Run", b =>
                {
                    b.HasOne("BytemountsAiStudio.Persistence.Entities.WorkflowVersion", "WorkflowVersion")
                        .WithMany("Runs")
                        .HasForeignKey("WorkflowVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_runs_workflow_versions_workflow_version_id");

                    b.Navigation("WorkflowVersion");
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.Topic", b =>
                {
                    b.HasOne("BytemountsAiStudio.Persistence.Entities.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_topics_channels_channel_id");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.WorkflowVersion", b =>
                {
                    b.HasOne("BytemountsAiStudio.Persistence.Entities.Workflow", "Workflow")
                        .WithMany("Versions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_versions_workflows_workflow_id");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.Run", b =>
                {
                    b.Navigation("NodeExecutions");
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.Workflow", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("BytemountsAiStudio.Persistence.Entities.WorkflowVersion", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
